import assert from "node:assert/strict";
import test from "node:test";
import { analyzeMonorepo } from "../../dist/application/repository/monorepo-service.js";
const snapshot=(nodes,edges=[])=>({schemaVersion:1,analyzerVersion:"0.9.2",repository:"/repo",commit:"abc",configurationFingerprint:"f",nodes,edges,metadata:{}});
test("0.9.2 detects package boundaries and dependency direction",()=>{const a={id:"a",type:"Package",attributes:{name:"a",rootPath:"packages/a"}};const b={id:"b",type:"Package",attributes:{name:"b",rootPath:"packages/b"}};const e={id:"e",source:"a",target:"b",type:"DEPENDS_ON",confidence:"EXACT",evidence:[],sourceCommit:"abc"};const r=analyzeMonorepo(snapshot([a,b],[e]));assert.equal(r.isMonorepo,true);assert.equal(r.packageCount,2);assert.deepEqual(r.packages.find(x=>x.id==="a").dependencies,["b"]);assert.deepEqual(r.packages.find(x=>x.id==="b").dependents,["a"]);});
test("0.9.2 maps source files and package test projects",()=>{const p={id:"a",type:"Package",attributes:{name:"a",rootPath:"packages/a"}};const f={id:"f",type:"File",attributes:{path:"packages/a/src/index.ts",packageId:"a"}};const t={id:"t",type:"TestProject",attributes:{framework:"vitest",rootPath:"packages/a"}};const e={id:"e",source:"a",target:"t",type:"CONTAINS",confidence:"EXACT",evidence:[],sourceCommit:"abc"};const r=analyzeMonorepo(snapshot([p,f,t],[e]));assert.equal(r.packages[0].sourceFiles,1);assert.deepEqual(r.packages[0].testProjects,["t"]);});
test("0.9.2 propagates package impact through reverse workspace dependencies",()=>{const a={id:"a",type:"Package",attributes:{name:"a",rootPath:"packages/a"}};const b={id:"b",type:"Package",attributes:{name:"b",rootPath:"packages/b"}};const f={id:"f",type:"File",attributes:{path:"packages/b/src/index.ts",packageId:"b"}};const e={id:"e",source:"a",target:"b",type:"DEPENDS_ON",confidence:"EXACT",evidence:[],sourceCommit:"abc"};const r=analyzeMonorepo(snapshot([a,b,f],[e]),["f"]);assert.deepEqual(r.impactedPackages,["a","b"]);});
test("0.9.2 remains deterministic",()=>{const p={id:"a",type:"Package",attributes:{name:"a",rootPath:"packages/a"}};assert.deepEqual(analyzeMonorepo(snapshot([p])),analyzeMonorepo(snapshot([p])));});
test("0.9.2 does not invent cross-package dependencies",()=>{const a={id:"a",type:"Package",attributes:{name:"a",rootPath:"packages/a"}};const b={id:"b",type:"Package",attributes:{name:"b",rootPath:"packages/b"}};const r=analyzeMonorepo(snapshot([a,b]));assert.deepEqual(r.packages[0].dependencies,[]);assert.deepEqual(r.packages[1].dependents,[]);});
