export * from "./contracts.js";
export type { GraphSnapshot, GraphNode, GraphEdge } from "../domain/graph/model.js";
export type { ChangeIntelligenceResult, UnifiedChange, ChangeRisk, ChangeUncertainty } from "../domain/change-intelligence.js";
export type { Impact } from "../domain/impact/model.js";
export type { TestImpact, TestImpactSummary } from "../domain/impact/test-impact.js";
export type { ExecutionPlan } from "../domain/workflow/execution-plan.js";
export type { Evidence, Confidence, Provenance } from "../domain/evidence/model.js";
export type { GctgConfiguration, ResolvedConfiguration, ConfigurationUpdateResult } from "../domain/configuration/model.js";
export { analyzeRepositoryEcosystem } from "../application/repository/ecosystem-service.js";
export { analyzeMonorepo } from "../application/repository/monorepo-service.js";
export type { MonorepoAnalysis, MonorepoPackage, MonorepoWorkspace } from "../application/repository/monorepo-service.js";
export type { RepositoryEcosystem, EcosystemCapability, EcosystemSupport } from "../application/repository/ecosystem-service.js";
export type { HistoricalIntelligence, HistoricalCommit, HistoricalSymbolTransition, HistoricalDependencyTransition, HistoricalTestImpactTransition, HistoricalUncertainty } from "../domain/historical-intelligence.js";
export { HistoricalIntelligenceService } from "../application/history/historical-intelligence-service.js";
export type { HistoricalIntelligenceInput, HistoricalSnapshotLoader } from "../application/history/historical-intelligence-service.js";
export type { CiAnalysisResult, CiFormat } from "../domain/ci.js";
export type { CiAnalysisContract, DiagnosticsContract } from "./contracts.js";
export type { OperationDiagnostics } from "../domain/diagnostics.js";
